auth-server: http://127.0.0.1:8080 # sso-server地址
server:
  context-path: /c4
  port: 8084
security:
  oauth2:
    client:
      client-id: c412345
      client-secret: 12345678
      user-authorization-uri: ${auth-server}/oauth/authorize #请求认证的地址
      access-token-uri: ${auth-server}/oauth/token #请求令牌的地址
    resource:
      jwt:
        key-uri: ${auth-server}/oauth/token_key #解析jwt令牌所需要密钥的地址